package graph

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

// GenerateJSMap gera um arquivo .js exportando o array de URLs.
func GenerateJSMap(urls []string, outputJS string, maxNodes int) error {
	nodeSet := make(map[string]struct{}, len(urls))
	for _, u := range urls {
		if u != "" {
			nodeSet[u] = struct{}{}
		}
	}
	nodes := make([]string, 0, len(nodeSet))
	for n := range nodeSet {
		nodes = append(nodes, n)
	}
	if len(nodes) > maxNodes {
		fmt.Fprintf(os.Stderr, "Warning: Limiting to %d URLs in JS map (from %d)\n", maxNodes, len(nodes))
		nodes = nodes[:maxNodes]
	}
	sort.Strings(nodes)

	f, err := os.Create(outputJS)
	if err != nil {
		return fmt.Errorf("error creating JS file: %w", err)
	}
	defer f.Close()

	var sb strings.Builder
	sb.WriteString("// URL Map generated by grau\n")
	fmt.Fprintf(&sb, "// Total URLs: %d\n", len(nodes))
	sb.WriteString("const urlMap = [\n")
	for i, u := range nodes {
		escaped := strings.ReplaceAll(u, `"`, `\"`)
		if i < len(nodes)-1 {
			fmt.Fprintf(&sb, "  \"%s\",\n", escaped)
		} else {
			fmt.Fprintf(&sb, "  \"%s\"\n", escaped)
		}
	}
	sb.WriteString("];\n")
	sb.WriteString("export default urlMap;\n")

	if _, err := f.WriteString(sb.String()); err != nil {
		return err
	}

	fmt.Printf("Generated JS map: %s (%d URLs)\n", outputJS, len(nodes))
	return nil
}
